[buildpack]
name = "Astro"
version = "0.1.0"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "gliderlabs/herokuish:latest"

[[stacks]]
id = "dokku"

[[stacks]]
id = "herokuish"